[package]
name = "rlw"
version = "0.1.0"
edition = "2021"
authors = ["Jayden Elliott <jayden.elliott@outlook.com>"]

[lib]
name = "rlw"
path = "src/lib/lib.rs"

# TODO: CLEAN THIS UP
[dependencies]
tonic = {version = "0.6.2", features = ["transport", "tls" , "tls-roots"] }
rustls = {version = "0.19.1", features = ["dangerous_configuration"]}
rustls-native-certs = "0.6.1"
rustls-pemfile = "0.3.0"
tokio-rustls = "0.15.0"
prost = "0.9"
log = "0.4.16"
env_logger = "0.9.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros", "sync", "time", "fs"] } 
tokio-stream = "0.1.8"
structopt = "0.3.26"
serde_json = "1.0.79"

[build-dependencies]
tonic-build = "0.6.0"
